# Generated by Django 4.2.4 on 2023-08-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artiles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='artiles',
            name='anons',
            field=models.CharField(default='Анонс', max_length=250, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='artiles',
            name='title',
            field=models.CharField(default='Новость', max_length=50, verbose_name='Название'),
        ),
    ]
