# Generated by Django 4.2.4 on 2023-08-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_artiles_options_artiles_anons_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artiles',
            new_name='Articles',
        ),
    ]
